### ISSUE TITLE
host and port specification

### ISSUE THREAD

**Issue by dillonbuhl** [gregoryng/navcoldex_gnss_server#2]
If I'm running the server program as a local feed to the GUI, what should I specify for --host and --port?
Should I always run it on port 4040?
Not quite clear, should I give it my local ip address as host?...

**Comment by gregoryng** [comment]
You should be able to let it use the defaults, which are defined here:

https://github.com/gregoryng/navcoldex_gnss_server/blob/7462c166de2a8b0afd27b66826d033efe9b324e1/server.py#L199-L200

So you should just be able to run

```bash
./server.py
```

Are you seeing something on the GUI client that seems to indicate that it's not finding it? I think the client normally looks for it on 4040, which is why you normally don't want to specify the `--port` option.

**Comment by dillonbuhl** [comment]
so, is '--interval' the server connection listening update interval, or the rate that GNSS message sets come in?

**Comment by gregoryng** [comment]
Interval is unrelated to network connection.

It's the rate that the messages get sent from the server to the client (regardless of the rate of nmea packets)
